export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",

  VIEW_USERS: "VIEW_USERS",
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  DELETE_USER: "DELETE_USER",

  VIEW_COURSE: "VIEW_COURSE",
  CREATE_COURSE: "CREATE_COURSE",
  UPDATE_COURSE: "UPDATE_COURSE",

  VIEW_ASSIGNMENTS: "VIEW_ASSIGNMENTS",

  USE_WORKSPACE: "USE_WORKSPACE",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
