import { Role } from "@/contants/roles";
import { Permission, PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  ADMIN: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.USE_WORKSPACE,
  ],

  PROFESSOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.USE_WORKSPACE,
  ],

  STUDENT: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
  ],
};
