import { Role } from "@/contants/roles";
import { Permission, PERMISSIONS } from "./permissions";

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  // =====================
  // ADMIN (FULL ACCESS)
  // =====================
  ADMIN: [
    // overview
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,

    // users & roles
    PERMISSIONS.VIEW_USERS,
    PERMISSIONS.CREATE_USER,
    PERMISSIONS.UPDATE_USER,
    PERMISSIONS.DELETE_USER,

    PERMISSIONS.MANAGE_ROLES,
    PERMISSIONS.MANAGE_PERMISSIONS,

    // academics
    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.UPDATE_COURSE,
    PERMISSIONS.DELETE_COURSE,

    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.GRADE_ASSIGNMENTS,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.VIEW_ATTENDANCE,

    // workspace
    PERMISSIONS.USE_WORKSPACE,
    PERMISSIONS.MANAGE_PROJECTS,
    PERMISSIONS.SUBMIT_PROJECTS,

    // content
    PERMISSIONS.MANAGE_CONTENT,
    PERMISSIONS.MANAGE_FILES,

    // organization
    PERMISSIONS.MANAGE_DEPARTMENTS,

    // monitoring (IMPORTANT)
    PERMISSIONS.VIEW_SYSTEM_MONITORING,
    PERMISSIONS.VIEW_LOGS,
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_PERFORMANCE,
    PERMISSIONS.VIEW_ERRORS,

    // settings
    PERMISSIONS.MANAGE_SETTINGS,
    PERMISSIONS.MANAGE_SECURITY,
    PERMISSIONS.MANAGE_BACKUP,

    // support
    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.MANAGE_TICKETS,
    PERMISSIONS.SEND_FEEDBACK,
  ],

  // =====================
  // PROFESSOR (TEACHING FOCUS)
  // =====================
  PROFESSOR: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,
    PERMISSIONS.VIEW_REPORTS,

    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.CREATE_COURSE,
    PERMISSIONS.UPDATE_COURSE,

    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.CREATE_ASSIGNMENTS,
    PERMISSIONS.GRADE_ASSIGNMENTS,

    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.VIEW_ATTENDANCE,

    PERMISSIONS.USE_WORKSPACE,

    PERMISSIONS.VIEW_TICKETS,
    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.SEND_FEEDBACK,
  ],

  // =====================
  // STUDENT (LIMITED ACCESS)
  // =====================
  STUDENT: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_NOTIFICATIONS,

    PERMISSIONS.VIEW_COURSE,
    PERMISSIONS.VIEW_ASSIGNMENTS,
    PERMISSIONS.VIEW_GRADES,
    PERMISSIONS.VIEW_ATTENDANCE,

    PERMISSIONS.SUBMIT_PROJECTS,
    PERMISSIONS.USE_WORKSPACE,

    PERMISSIONS.CREATE_TICKETS,
    PERMISSIONS.SEND_FEEDBACK,
  ],
};
