spring.application.name=backend

#Port
server.port=8080

#Frontend
app.cors.allowed-origins=http://localhost:3000

#JWT
jwt.secret=acadex_super_secret_key_which_is_long_enough_123456789

#Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/micro-user-service-db
spring.datasource.username=postgres
spring.datasource.password=07132002
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always

#Prometheus Configuration
management.endpoint.prometheus.enabled=true
management.prometheus.metrics.export.enabled=true

#Swagger
springdoc.swagger-ui.path=/api-docs

#Redis Configuration
spring.redis.host=localhost
spring.redis.port=6379

#Logging Configuration
logging.level.org.springframework.cache=DEBUG
logging.level.org.springframework.data.redis=DEBUG

# Cipher configuration used by CipherUtil in the common library
# algorithm defines the encryption mode and padding (recommended: AES/GCM/NoPadding for security)
# key must be 16, 24, or 32 characters long depending on AES strength (AES-128/192/256)
cipher.algorithm=AES
cipher.key=Th3W0r!dbE!0n9$T0g1@2etH3tr*eg0E